### ISSUE TITLE
Hardware Settings and Connection Details. 

### ISSUE THREAD

**Issue by XxSNiPxX** [tj-scherer/rot2prog#4]
Simulator works fine but connecting the MD01 SPID controller to the computer via USB , changing the protocol to SPID Rot2prog fails to receive any response from the controller

What are the necessary settings on the controller and PC needed to get it to work? Are there any specific drivers required for this library to work? Could you share any more details about setting up the hardware/software perquisites necessary?

Thanks,
Rishabh

**Comment by timothyscherer** [comment]
Does the MD01 use the same protocol? This was never tested with that controller, so I am unsure. There are no drivers required for the library. Were you able to make the serial connection successfully? As long as the serial port (COM on Windows) is accessible the python should be able to connect to it. The user manual for that device does not refer to the ROT2Prog serial protocol, just their own program to control it with a serial port.

**Comment by timothyscherer** [comment]
Closed for inactivity
