### ISSUE TITLE
Rot2Prog.status() Delay

### ISSUE THREAD

**Issue by phelps-matthew** [tj-scherer/rot2prog#5]
Thank you for sharing this package. I have been able to successfully drive my rotors but am experiencing an odd issue related to the use of ROT2Prog.status() (or ROTn_CMD_GET_ANGLES).

When sending the status command, there appears to be a stack of reponses formed that is not poppable until the rotor reaches its destination. For example, setting AZ for 0 deg to 100 deg, repeated querying of the status yields AZ=0 until the rotor arrives at AZ=100, in which I must command the status about 12-13 times until I get the right response.

Relatedly, I have noticed that if I do not send and status queries while the rotor is moving and wait until it reaches its final destination, I must still send about 12-13 requests until it converges on the current readout. 

In troubleshooting the issue, I have tried adjusting the timeout and interbyte timeout up and down by a few orders of magnitude, but with no success.

I'm wondering, what type of error do you think might be producing this behavior? I am using baudrate of 115200 as per the default settings I received from my vendor. It does not seem that I am dropping any responses since they all eventually arrive after popping the whole stack. Appreciate any insight you might have, thanks!

**Comment by timothyscherer** [comment]
You could try a serial analyzer to determine when the packets are actually arriving. This sounds like your controller may be sending status packets without a request. Currently, the python program only calls `_recv_response()` after sending a stop or status command.

Looking back, the better approach here (although slightly more complex) would have been to run `_recv_response()` inside a daemon, and just update some class members every time a response is received.

Do the response packets every contain a value other than 0 or 100? If your unit generates its own packets, I could see that it would be filling the buffer with stale data that is never read until you send a status command, hence why you would need more status requests to clear out all of that data.

**Comment by phelps-matthew** [comment]
Thanks for the response! I have determined that my problem arises from the response packet coming from ```set(az, el)```. I am not sure if the protocol has at all changed but my reference to Rot2Prog protocol version 2.0 (from RFHamDesign) indicates that CMD_SET_ANGLES actually yields a response packet. 

Thus, by simply adding a ```return self._recv_response()``` at the end of the ```set``` method my issue with receiving a response from the (n-1) status request is fixed. In my application, my frequent calling of ```set``` effectively added another response to the queue, thereby requiring many calls to ```status``` to get the right response.

**Comment by timothyscherer** [comment]
Yeah this "standard" isn't so standard it seems... gathering information for my use case was difficult as it was. Glad you were able to resolve your issue.
